version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_TYPE: sqlite
      DATABASE_PATH: ./database.sqlite3
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "
      npm install &&
      npm run start:dev
      "
